services:
  - type: web
    name: spring-boot-app
    env: docker
    repo: https://github.com/your-repo/real-time-chat-application # Replace with your repository URL
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromService:
          type: postgres
          name: chat-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromService:
          type: postgres
          name: chat-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromService:
          type: postgres
          name: chat-db
          property: password

  - type: postgres
    name: chat-db
    ipAllowList: [] # Allow all IPs to connect to the database
