# This is the configuration file for Render.

# Top-level key for databases
databases:
  - name: "chat-database"
    region: "oregon"
    plan: "free"

# Top-level key for services
services:
  # The Java Spring Boot Application
  - type: "web"
    name: "real-time-chat-app"
    runtime: "docker"
    region: "oregon"
    plan: "free"
    dockerfilePath: ./Dockerfile
    # CORRECTED: The start command now uses the PORT variable provided by Render.
    startCommand: "java -jar app.jar --server.port=${PORT}"
    envVars:
      - key: "JAVA_VERSION"
        value: "17"
      - key: "DATABASE_URL"
        fromDatabase:
          name: "chat-database"
          property: "connectionString"
      - key: "TOKEN_SIGNING_KEY"
        value: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"
