# This is the configuration file for Render.

databases:
  - name: "chat-database"
    region: "oregon"
    plan: "free"

services:
  - type: "web"
    name: "real-time-chat-app"
    runtime: "docker"
    region: "oregon"
    plan: "free"
    dockerfilePath: ./Dockerfile
    envVars:
      - key: "JAVA_VERSION"
        value: "17"
      - key: "SPRING_PROFILES_ACTIVE"
        value: "prod"
      - key: "SERVER_PORT"
        value: "10000"
      # Construct the JDBC URL in the classic format to ensure compatibility.
      - key: "SPRING_DATASOURCE_URL"
        value: "jdbc:postgresql://${chat-database.host}:${chat-database.port}/${chat-database.database}"
      - key: "SPRING_DATASOURCE_USERNAME"
        fromDatabase:
          name: "chat-database"
          property: "user"
      - key: "SPRING_DATASOURCE_PASSWORD"
        fromDatabase:
          name: "chat-database"
          property: "password"
      - key: "TOKEN_SIGNING_KEY"
        value: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"
