# This is the configuration file for Render.

# Top-level key for databases
databases:
  - name: "chat-database"
    region: "oregon"
    plan: "free"

# Top-level key for services
services:
  # The Java Spring Boot Application
  - type: "web"
    name: "real-time-chat-app"
    runtime: "java" # CORRECTED: Use 'runtime' instead of 'env'
    region: "oregon"
    plan: "free"
    buildCommand: "./mvnw package"
    startCommand: "java -jar target/*.jar"
    envVars:
      # Set the Java version for the build
      - key: "JAVA_VERSION"
        value: "17"
      # Set your JWT secret key
      - key: "TOKEN_SIGNING_KEY"
        value: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"
      # NOTE: We no longer need SPRING_DATASOURCE variables here.
      # The postgresql-datasource-url-parser library and Render's
      # default DATABASE_URL environment variable handle it automatically.