# This is the configuration file for Render.
# It defines all the services for your project.

# Top-level key for databases
databases:
  - name: "chat-database"
    region: "oregon"
    plan: "free"

# Top-level key for services
services:
  # The Java Spring Boot Application
  - type: "web"
    name: "real-time-chat-app"
    env: "java"
    region: "oregon"
    plan: "free"
    buildCommand: "./mvnw package"
    startCommand: "java -jar target/*.jar"
    envVars:
      # Set the Java version for the build (as a string)
      - key: "JAVA_VERSION"
        value: "17"
      # Link the database to this web service.
      - key: "SPRING_DATASOURCE_URL"
        fromDatabase:
          name: "chat-database"
          property: "jdbcConnectionString"
      - key: "SPRING_DATASOURCE_USERNAME"
        fromDatabase:
          name: "chat-database"
          property: "user"
      - key: "SPRING_DATASOURCE_PASSWORD"
        fromDatabase:
          name: "chat-database"
          property: "password"
      # Set your other secrets (as a single-line string)
      - key: "TOKEN_SIGNING_KEY"
        value: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"